name: Build, Deploy, and Analyze with SonarCloud

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Build with Maven
      - name: Build with Maven
        run: mvn clean install

      # Upload the JAR as an artifact
      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: bus-booking-app
          path: target/simple-parcel-service-app-1.0-SNAPSHOT.jar

  # SonarCloud Analysis Job
  sonarcloud:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up SonarCloud
      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v1
        with:
          organization: ${{ secrets.SONAR_ORG_KEY }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Run SonarCloud Analysis
      - name: SonarCloud Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }} -Dsonar.java.binaries=target/classes
