name: Build, Deploy, and Analyze

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Allow for manual trigger via GitHub UI

jobs:
  # Call the Java and Maven setup workflow
  java-maven-setup:
    uses: ./.github/workflows/setup-java-maven-setup.yml  # Reference to the consolidated Java and Maven setup workflow

  # # Call the build and artifact workflow
  # build-and-artifact:
  #   uses: ./.github/workflows/build-and-artifact.yml  # Reference to the build workflow

  # # Call the Spring Boot run and stop workflow
  # springboot-run-stop:
  #   uses: ./.github/workflows/springboot-run-stop.yml  # Reference to the Spring Boot workflow

  # # Call the SonarCloud analysis workflow
  # sonarcloud-analysis:
  #   uses: ./.github/workflows/sonarcloud-analysis.yml  # Reference to the SonarCloud analysis workflow
  #   with:
  #     sonar-token: ${{ secrets.SONAR_TOKEN }}
  #     sonar-org: your-organization  # Replace with your actual SonarCloud organization
  #     sonar-host-url: https://sonarcloud.io
