name: Build, Deploy, and Analyze

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-java-maven:
    uses: ./.github/workflows/setup-java-maven.yml

  build-and-artifact:
    uses: ./.github/workflows/build-and-artifact.yml
    needs: setup-java-maven

  springboot-run-stop:
    uses: ./.github/workflows/springboot-run-stop.yml
    needs: build-and-artifact

  sonarcloud-analysis:
    uses: ./.github/workflows/sonarcloud-analysis.yml
    needs: build-and-artifact
